/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign out this device */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign out everywhere */
    post: operations['logout_all_devices'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/otp/request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a login code by SMS */
    post: operations['request_otp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/otp/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange a login code for tokens */
    post: operations['verify_otp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate a refresh token */
    post: operations['refresh_tokens'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/cities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Cities */
    get: operations['list_cities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Health
     * @description Liveness: the process is up. Does not touch dependencies.
     */
    get: operations['get_health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Readiness
     * @description Readiness: database, Redis and object storage are reachable.
     */
    get: operations['get_readiness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search active listings (no sign-in required) */
    get: operations['search_listings'];
    put?: never;
    /** Create a draft listing */
    post: operations['create_listing'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings/mine': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Your own listings, in any status */
    get: operations['list_my_listings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings/moderation/queue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listings awaiting review (admin only) */
    get: operations['list_moderation_queue'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings/{listing_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listing detail (private fields only for the seller) */
    get: operations['get_listing'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Listing */
    patch: operations['update_listing'];
    trace?: never;
  };
  '/listings/{listing_id}/manage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The seller's own view, including the private floor price */
    get: operations['get_my_listing'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings/{listing_id}/moderate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve or reject a listing (admin only) */
    post: operations['moderate_listing'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings/{listing_id}/photos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload one photo (JPEG, PNG or WebP) */
    post: operations['upload_listing_photo'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings/{listing_id}/photos/{photo_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Listing Photo */
    delete: operations['delete_listing_photo'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings/{listing_id}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit a draft for review */
    post: operations['publish_listing'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings/{listing_id}/sold': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark as sold and record the final price */
    post: operations['mark_listing_sold'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings/{listing_id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Hide or republish your listing */
    put: operations['set_listing_status'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/listings/{listing_id}/status-history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Why this listing is in its current status */
    get: operations['get_listing_status_history'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/makes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Makes */
    get: operations['list_makes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/models': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Models */
    get: operations['list_models'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/showrooms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a showroom (the creator becomes its owner) */
    post: operations['create_showroom'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/showrooms/{showroom_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Showroom */
    get: operations['get_showroom'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Showroom */
    patch: operations['update_showroom'];
    trace?: never;
  };
  '/showrooms/{showroom_id}/staff': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Staff list (visible to the showroom's own staff) */
    get: operations['list_showroom_staff'];
    put?: never;
    /** Add a staff member by phone number */
    post: operations['add_showroom_staff'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/showrooms/{showroom_id}/staff/{staff_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Showroom Staff */
    delete: operations['remove_showroom_staff'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/showrooms/{showroom_id}/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark a showroom as verified (admin only) */
    post: operations['verify_showroom'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/trims': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Trims */
    get: operations['list_trims'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations['get_me'];
    put?: never;
    post?: never;
    /** Delete your account and personal data (PDPL) */
    delete: operations['delete_my_account'];
    options?: never;
    head?: never;
    /** Update Me */
    patch: operations['update_me'];
    trace?: never;
  };
  '/users/me/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download everything we store about you (PDPL) */
    get: operations['export_my_data'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me/role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Switch between buying and selling */
    put: operations['set_my_role'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public profile (never includes the phone number) */
    get: operations['get_user'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Ack */
    Ack: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /**
     * BodyType
     * @enum {string}
     */
    BodyType: 'sedan' | 'suv' | 'pickup' | 'hatchback' | 'coupe' | 'van' | 'other';
    /** Body_upload_listing_photo */
    Body_upload_listing_photo: {
      /**
       * File
       * @description Image file, up to 8 MB
       */
      file: string;
    };
    /** CityOut */
    CityOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name Ar */
      name_ar: string;
      /** Name En */
      name_en: string;
      /** Region Ar */
      region_ar: string;
      /** Region En */
      region_en: string;
      /** Slug */
      slug: string;
    };
    /** DependencyCheck */
    DependencyCheck: {
      /** Error */
      error?: string | null;
      /** Latency Ms */
      latency_ms: number;
      /** Ok */
      ok: boolean;
    };
    /**
     * ErrorResponse
     * @description Every error body. `code` is stable; clients translate it.
     */
    ErrorResponse: {
      /** Code */
      code: string;
      /** Details */
      details?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * FuelType
     * @enum {string}
     */
    FuelType: 'petrol' | 'diesel' | 'hybrid' | 'electric';
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Environment */
      environment: string;
      /** Service */
      service: string;
      /**
       * Status
       * @constant
       */
      status: 'ok';
      /** Version */
      version: string;
    };
    /**
     * Language
     * @enum {string}
     */
    Language: 'ar' | 'en';
    /** ListingCreate */
    ListingCreate: {
      /**
       * Accident History Declared
       * @default false
       */
      accident_history_declared: boolean;
      /** Asking Price Sar */
      asking_price_sar: number;
      body_type?: components['schemas']['BodyType'] | null;
      /**
       * City Id
       * Format: uuid
       */
      city_id: string;
      /** Color Ar */
      color_ar?: string | null;
      /** Description Ar */
      description_ar?: string | null;
      /** Description En */
      description_en?: string | null;
      /** Engine */
      engine?: string | null;
      /** Floor Price Sar */
      floor_price_sar?: number | null;
      /** @default petrol */
      fuel_type: components['schemas']['FuelType'];
      /**
       * Make Id
       * Format: uuid
       */
      make_id: string;
      /** Mileage Km */
      mileage_km: number;
      /**
       * Model Id
       * Format: uuid
       */
      model_id: string;
      /**
       * Negotiable
       * @default true
       */
      negotiable: boolean;
      /** @default saudi */
      regional_spec: components['schemas']['RegionalSpec'];
      /**
       * Service History Declared
       * @default false
       */
      service_history_declared: boolean;
      /** Showroom Id */
      showroom_id?: string | null;
      /** @default automatic */
      transmission: components['schemas']['Transmission'];
      /** Trim Id */
      trim_id?: string | null;
      /** Year */
      year: number;
    };
    /** ListingDetail */
    ListingDetail: {
      /** Accident History Declared */
      accident_history_declared: boolean;
      /** Asking Price Sar */
      asking_price_sar: number;
      body_type: components['schemas']['BodyType'] | null;
      /**
       * City Id
       * Format: uuid
       */
      city_id: string;
      /** Color Ar */
      color_ar: string | null;
      cover_photo?: components['schemas']['PhotoOut'] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Description Ar */
      description_ar: string | null;
      /** Description En */
      description_en: string | null;
      /** Engine */
      engine: string | null;
      fuel_type: components['schemas']['FuelType'];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Make Id
       * Format: uuid
       */
      make_id: string;
      /** Mileage Km */
      mileage_km: number;
      /**
       * Model Id
       * Format: uuid
       */
      model_id: string;
      /** Negotiable */
      negotiable: boolean;
      /**
       * Photos
       * @default []
       */
      photos: components['schemas']['PhotoOut'][];
      /** Published At */
      published_at: string | null;
      regional_spec: components['schemas']['RegionalSpec'];
      /**
       * Seller Id
       * Format: uuid
       */
      seller_id: string;
      seller_type: components['schemas']['SellerType'];
      /** Service History Declared */
      service_history_declared: boolean;
      /** Showroom Id */
      showroom_id: string | null;
      /** Sold At */
      sold_at: string | null;
      status: components['schemas']['ListingStatus'];
      transmission: components['schemas']['Transmission'];
      /** Trim Id */
      trim_id: string | null;
      /** Views Count */
      views_count: number;
      /** Year */
      year: number;
    };
    /** ListingPage */
    ListingPage: {
      /** Items */
      items: components['schemas']['ListingSummary'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * ListingStatus
     * @description Every non-active status carries a reason the seller can read (see StatusReasonCode).
     * @enum {string}
     */
    ListingStatus:
      'draft' | 'pending_review' | 'active' | 'hidden' | 'rejected' | 'sold' | 'expired';
    /**
     * ListingSummary
     * @description What a search result shows. Deliberately excludes the seller's private fields.
     */
    ListingSummary: {
      /** Asking Price Sar */
      asking_price_sar: number;
      /**
       * City Id
       * Format: uuid
       */
      city_id: string;
      cover_photo?: components['schemas']['PhotoOut'] | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Make Id
       * Format: uuid
       */
      make_id: string;
      /** Mileage Km */
      mileage_km: number;
      /**
       * Model Id
       * Format: uuid
       */
      model_id: string;
      /** Published At */
      published_at: string | null;
      seller_type: components['schemas']['SellerType'];
      status: components['schemas']['ListingStatus'];
      /** Trim Id */
      trim_id: string | null;
      /** Year */
      year: number;
    };
    /**
     * ListingUpdate
     * @description Every field optional; only what is sent changes.
     */
    ListingUpdate: {
      /** Accident History Declared */
      accident_history_declared?: boolean | null;
      /** Asking Price Sar */
      asking_price_sar?: number | null;
      body_type?: components['schemas']['BodyType'] | null;
      /** City Id */
      city_id?: string | null;
      /** Color Ar */
      color_ar?: string | null;
      /** Description Ar */
      description_ar?: string | null;
      /** Description En */
      description_en?: string | null;
      /** Engine */
      engine?: string | null;
      /** Floor Price Sar */
      floor_price_sar?: number | null;
      fuel_type?: components['schemas']['FuelType'] | null;
      /** Mileage Km */
      mileage_km?: number | null;
      /** Negotiable */
      negotiable?: boolean | null;
      regional_spec?: components['schemas']['RegionalSpec'] | null;
      /** Service History Declared */
      service_history_declared?: boolean | null;
      transmission?: components['schemas']['Transmission'] | null;
      /** Trim Id */
      trim_id?: string | null;
      /** Year */
      year?: number | null;
    };
    /** MakeOut */
    MakeOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name Ar */
      name_ar: string;
      /** Name En */
      name_en: string;
      /** Slug */
      slug: string;
    };
    /** MarkSoldIn */
    MarkSoldIn: {
      /** Final Price Sar */
      final_price_sar: number;
    };
    /** ModerationIn */
    ModerationIn: {
      /** Approve */
      approve: boolean;
      /** Note */
      note?: string | null;
      reason_code?: components['schemas']['StatusReasonCode'] | null;
    };
    /** OtpRequestIn */
    OtpRequestIn: {
      /** @default ar */
      language: components['schemas']['Language'];
      /**
       * Phone
       * @example 0501234567
       */
      phone: string;
    };
    /** OtpRequestOut */
    OtpRequestOut: {
      /** Debug Code */
      debug_code?: string | null;
      /** Expires In S */
      expires_in_s: number;
      /** Phone */
      phone: string;
    };
    /** OtpVerifyIn */
    OtpVerifyIn: {
      /** Code */
      code: string;
      /** Phone */
      phone: string;
    };
    /** PhotoOut */
    PhotoOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Position */
      position: number;
      /** Url */
      url: string;
    };
    /**
     * PublicUserOut
     * @description What other users may see. Never includes the phone number.
     */
    PublicUserOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identity Verified */
      identity_verified: boolean;
      /** Name */
      name: string | null;
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /** Checks */
      checks: {
        [key: string]: components['schemas']['DependencyCheck'];
      };
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'unavailable';
    };
    /** RefreshIn */
    RefreshIn: {
      /** Refresh Token */
      refresh_token: string;
    };
    /**
     * RegionalSpec
     * @description Where the car was originally specified for; it affects price in the Saudi market.
     * @enum {string}
     */
    RegionalSpec: 'saudi' | 'gcc' | 'american' | 'other';
    /**
     * RoleUpdate
     * @description A buyer can become a seller themselves; admin roles are granted by an admin only.
     */
    RoleUpdate: {
      role: components['schemas']['UserRole'];
    };
    /**
     * SellerListingDetail
     * @description The seller's own view: adds the private fields only they may see.
     */
    SellerListingDetail: {
      /** Accident History Declared */
      accident_history_declared: boolean;
      /** Asking Price Sar */
      asking_price_sar: number;
      body_type: components['schemas']['BodyType'] | null;
      /**
       * City Id
       * Format: uuid
       */
      city_id: string;
      /** Color Ar */
      color_ar: string | null;
      cover_photo?: components['schemas']['PhotoOut'] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Description Ar */
      description_ar: string | null;
      /** Description En */
      description_en: string | null;
      /** Engine */
      engine: string | null;
      /** Final Price Sar */
      final_price_sar: number | null;
      /** Floor Price Sar */
      floor_price_sar: number | null;
      fuel_type: components['schemas']['FuelType'];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Make Id
       * Format: uuid
       */
      make_id: string;
      /** Mileage Km */
      mileage_km: number;
      /**
       * Model Id
       * Format: uuid
       */
      model_id: string;
      /** Negotiable */
      negotiable: boolean;
      /**
       * Photos
       * @default []
       */
      photos: components['schemas']['PhotoOut'][];
      /** Published At */
      published_at: string | null;
      regional_spec: components['schemas']['RegionalSpec'];
      /**
       * Seller Id
       * Format: uuid
       */
      seller_id: string;
      seller_type: components['schemas']['SellerType'];
      /** Service History Declared */
      service_history_declared: boolean;
      /** Showroom Id */
      showroom_id: string | null;
      /** Sold At */
      sold_at: string | null;
      status: components['schemas']['ListingStatus'];
      status_reason_code: components['schemas']['StatusReasonCode'] | null;
      /** Status Reason Note */
      status_reason_note: string | null;
      transmission: components['schemas']['Transmission'];
      /** Trim Id */
      trim_id: string | null;
      /** Views Count */
      views_count: number;
      /** Year */
      year: number;
    };
    /**
     * SellerType
     * @enum {string}
     */
    SellerType: 'private' | 'showroom';
    /** ShowroomCreate */
    ShowroomCreate: {
      /**
       * City Id
       * Format: uuid
       */
      city_id: string;
      /** Commercial Registration Number */
      commercial_registration_number: string;
      /** Name Ar */
      name_ar: string;
      /** Name En */
      name_en?: string | null;
    };
    /** ShowroomOut */
    ShowroomOut: {
      /**
       * City Id
       * Format: uuid
       */
      city_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name Ar */
      name_ar: string;
      /** Name En */
      name_en: string | null;
      subscription_tier: components['schemas']['SubscriptionTier'];
      /** Verified */
      verified: boolean;
    };
    /** ShowroomStaffAdd */
    ShowroomStaffAdd: {
      /** Phone */
      phone: string;
      /** @default agent */
      role: components['schemas']['ShowroomStaffRole'];
    };
    /** ShowroomStaffOut */
    ShowroomStaffOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      role: components['schemas']['ShowroomStaffRole'];
      user: components['schemas']['PublicUserOut'];
    };
    /**
     * ShowroomStaffRole
     * @enum {string}
     */
    ShowroomStaffRole: 'owner' | 'manager' | 'agent';
    /** ShowroomUpdate */
    ShowroomUpdate: {
      /** City Id */
      city_id?: string | null;
      /** Name Ar */
      name_ar?: string | null;
      /** Name En */
      name_en?: string | null;
    };
    /**
     * SortOrder
     * @enum {string}
     */
    SortOrder: 'newest' | 'price_asc' | 'price_desc' | 'mileage_asc' | 'year_desc';
    /**
     * StatusChangeIn
     * @description Seller-driven status change (hide or republish).
     */
    StatusChangeIn: {
      status: components['schemas']['ListingStatus'];
    };
    /** StatusEventOut */
    StatusEventOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      from_status: components['schemas']['ListingStatus'] | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Note */
      note: string | null;
      reason_code: components['schemas']['StatusReasonCode'] | null;
      to_status: components['schemas']['ListingStatus'];
    };
    /**
     * StatusReasonCode
     * @description Why a listing is not active. Clients translate these; we never send prose.
     * @enum {string}
     */
    StatusReasonCode:
      | 'seller_draft'
      | 'seller_hid'
      | 'seller_sold'
      | 'seller_republished'
      | 'awaiting_review'
      | 'approved'
      | 'missing_photos'
      | 'incomplete_details'
      | 'suspected_duplicate'
      | 'price_anomaly'
      | 'prohibited_content'
      | 'contact_in_description'
      | 'suspected_fraud'
      | 'expired_unsold';
    /**
     * SubscriptionTier
     * @enum {string}
     */
    SubscriptionTier: 'free' | 'basic' | 'pro';
    /** TokensOut */
    TokensOut: {
      /** Access Token */
      access_token: string;
      /** Expires In S */
      expires_in_s: number;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      user: components['schemas']['UserOut'];
    };
    /**
     * Transmission
     * @enum {string}
     */
    Transmission: 'automatic' | 'manual';
    /** TrimOut */
    TrimOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Model Id
       * Format: uuid
       */
      model_id: string;
      /** Name Ar */
      name_ar: string;
      /** Name En */
      name_en: string;
      /** Slug */
      slug: string;
    };
    /**
     * UserOut
     * @description The signed-in user's own profile. Phone is only ever returned to that user.
     */
    UserOut: {
      /** City Id */
      city_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Identity Verified */
      identity_verified: boolean;
      /** Name */
      name: string | null;
      /** Phone */
      phone: string;
      preferred_language: components['schemas']['Language'];
      role: components['schemas']['UserRole'];
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: 'buyer' | 'seller' | 'showroom_staff' | 'admin';
    /** UserUpdate */
    UserUpdate: {
      /** City Id */
      city_id?: string | null;
      /** Name */
      name?: string | null;
      preferred_language?: components['schemas']['Language'] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VehicleModelOut */
    VehicleModelOut: {
      body_type?: components['schemas']['BodyType'] | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Make Id
       * Format: uuid
       */
      make_id: string;
      /** Name Ar */
      name_ar: string;
      /** Name En */
      name_en: string;
      /** Slug */
      slug: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ack'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_all_devices: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ack'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  request_otp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OtpRequestIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OtpRequestOut'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  verify_otp: {
    parameters: {
      query?: never;
      header?: {
        'user-agent'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OtpVerifyIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokensOut'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  refresh_tokens: {
    parameters: {
      query?: never;
      header?: {
        'user-agent'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokensOut'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_cities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CityOut'][];
        };
      };
    };
  };
  get_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  get_readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadinessResponse'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadinessResponse'];
        };
      };
    };
  };
  search_listings: {
    parameters: {
      query?: {
        /** @description Free text, Arabic or English */
        q?: string | null;
        make_id?: string | null;
        model_id?: string | null;
        trim_id?: string | null;
        city_id?: string | null;
        year_min?: number | null;
        year_max?: number | null;
        price_min?: number | null;
        price_max?: number | null;
        mileage_max?: number | null;
        body_type?: components['schemas']['BodyType'] | null;
        transmission?: components['schemas']['Transmission'] | null;
        fuel_type?: components['schemas']['FuelType'] | null;
        regional_spec?: components['schemas']['RegionalSpec'] | null;
        seller_type?: components['schemas']['SellerType'] | null;
        accident_free?: boolean | null;
        sort?: components['schemas']['SortOrder'];
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListingPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_listing: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ListingCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SellerListingDetail'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_my_listings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SellerListingDetail'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_moderation_queue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SellerListingDetail'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_listing: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListingDetail'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_listing: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ListingUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SellerListingDetail'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_my_listing: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SellerListingDetail'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  moderate_listing: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ModerationIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SellerListingDetail'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_listing_photo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_listing_photo'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PhotoOut'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_listing_photo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ack'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  publish_listing: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SellerListingDetail'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mark_listing_sold: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MarkSoldIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SellerListingDetail'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  set_listing_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StatusChangeIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SellerListingDetail'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_listing_status_history: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusEventOut'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_makes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MakeOut'][];
        };
      };
    };
  };
  list_models: {
    parameters: {
      query?: {
        /** @description Filter to one make */
        make_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VehicleModelOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_showroom: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ShowroomCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShowroomOut'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_showroom: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        showroom_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShowroomOut'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_showroom: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        showroom_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ShowroomUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShowroomOut'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_showroom_staff: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        showroom_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShowroomStaffOut'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_showroom_staff: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        showroom_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ShowroomStaffAdd'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShowroomStaffOut'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_showroom_staff: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        showroom_id: string;
        staff_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ack'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  verify_showroom: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        showroom_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShowroomOut'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_trims: {
    parameters: {
      query: {
        /** @description Model to list trims for */
        model_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrimOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
    };
  };
  delete_my_account: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ack'];
        };
      };
    };
  };
  update_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  export_my_data: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  set_my_role: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RoleUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PublicUserOut'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
